---
- name: Configure Jenkins Slave VM
  hosts: localhost
  gather_facts: True
  become: yes
  roles:
    - ansible-role-generic-setup
    - ansible-role-install-kvm
  tasks:
  - name: Install latest version of Java
    apt:
      name: default-jre
      state: present
  - name: Create dedicated jenkins user
    user:
      name: jenkins
      groups: libvirt
      state: present
      shell: /bin/bash
