---
- name: Configure Jenkins Slave VM
  hosts: localhost
  gather_facts: True
  become: yes
  roles:
    - ansible-role-generic-setup
    - ansible-role-install-kvm
  tasks:
  - name: Add Hashicorp GPG key
    get_url:
      url: https://apt.releases.hashicorp.com/gpg
      dest: /etc/apt/trusted.gpg.d/hashicorp.asc

  - name: Add Hashicorp repo
    apt_repository:
      repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
      state: present

  - name: Install Packer and Terraform
    apt:
      name: 
        - packer={{ packer_version }}
        - terraform
      allow_downgrade: yes
      update_cache: yes

  - name: Install latest version of Java
    apt:
      name: default-jre
      state: present

  - name: Create dedicated jenkins user
    user:
      name: jenkins
      groups: libvirt
      state: present
      shell: /bin/bash
